apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent_volume_name
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs_endpoint_name
    path: glusterfs_volume
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

