apiVersion: v1
kind: PersistentVolume
metadata:
  name: ppas-pv 
spec:
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /volumes/edb-95 
    server: 127.0.0.1 
  persistentVolumeReclaimPolicy: Retain 
