apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent_volume_claim_name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: persistent_volume_name
