apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent_volume_name
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: complete_path_to_volume_directory
    persistentVolumeReclaimPolicy: Retain